version: '3'

services:
  pdnsmaster:
    container_name: pdnsmanager
    env_file: .env
    image: pdnsmanager:latest
    build: "."
    restart: always
    ports:
            - "9999:80"
    networks:
      - default
